#:kivy 1.0.9

#<Buy>:
#    Button:
#        text:'Buy!'
#        id: BGreen
#        size_hint:(.3, .2)
#        pos: (root.width *0.3, root.height * 0.6)
#        on_press: root.coll(BGreen)#

#    Button:
##        text: 'B2'
#        id: B2
#        size_hint:(.3, .2)
#        pos: (root.width *0.6, root.height * 0.6)
#        on_press: root.draw(BGreen)
#        on_press: print root.enint2

<Exodus>:
    FloatLayout:

        Button:
            text:'Sell green'
            id: SGreen
            size_hint:(.3, .2)
            pos: (0, root.height * 0.8)
            on_press: root.action('sg')
            #on_press: root.txt_inpt2 = str(root.exo.GetPlayerStash()) 
        Button:
            text:'Sell red'
            id: SRed
            size_hint:(.3, .2)
            pos: (root.width *0.3, root.height * 0.8)
            on_press: root.action('sr')
            #on_press: root.txt_inpt2 = str(root.exo.GetPlayerStash())            
        Button:
            text:'Buy green'
            id: BGreen
            size_hint:(.3, .2)
            pos: (0, root.height * 0.6)
            on_press: root.action('bg') 
            #on_press: root.txt_inpt2 = str(root.exo.GetPlayerStash())
        Button:
            text:'Buy red'
            id: BGreen
            size_hint:(.3, .2)
            pos: (root.width *0.3, root.height * 0.6)
            on_press: root.action('br')
            #on_press: root.txt_inpt2 = str(root.exo.GetPlayerStash())



        ToggleButton:
            text:'2player'
            id:p2
            size_hint:(.2, .1)
            pos: (root.width *0.6, root.height * 0.9)
            group: 'playergroup'
            on_press: root.exo.SetRatio(2)
            on_press: root.add_player(root.exo.Players)                    


        ToggleButton:
            text:'3player'
            id:p3
            size_hint:(.2, .1)
            pos: (root.width *0.6, root.height * 0.8)
            group: 'playergroup'
            on_press: root.exo.SetRatio(3)          
        ToggleButton:
            text:'4player'
            id:p4
            size_hint:(.2, .1)
            pos: (root.width *0.6, root.height * 0.7)
            group: 'playergroup'
            on_press: root.exo.SetRatio(4)
        ToggleButton:
            text:'5player'
            id:p5
            size_hint:(.2, .1)
            pos: (root.width *0.6, root.height * 0.6)
            group: 'playergroup'
            on_press: root.exo.SetRatio(5)
        ToggleButton:
            text:'6player'
            id:p6
            size_hint:(.2, .1)
            pos: (root.width *0.6, root.height * 0.5)
            group: 'playergroup'
            on_press: root.exo.SetRatio(6)   



        ToggleButton:
            text:'round 1'
            id:r1
            size_hint:(.2, .1)
            pos: (root.width *0.8, root.height * 0.9)
            group: 'playerturn'
            on_press: root.exo.SetTurn(1)
            on_press: root.add_turn(root.exo.Turn)
        ToggleButton:
            text:'round 2'
            id:r2
            size_hint:(.2, .1)
            pos: (root.width *0.8, root.height * 0.8)
            group: 'playerturn'
            on_press: root.exo.SetTurn(2)
            on_press: root.add_turn(root.exo.Turn)                    
        ToggleButton:
            text:'round 3'
            id:r3
            size_hint:(.2, .1)
            pos: (root.width *0.8, root.height * 0.7)
            group: 'playerturn'
            on_press: root.exo.SetTurn(3)
            on_press: root.add_turn(root.exo.Turn)                    
        ToggleButton:
            text:'round 4'
            id:r4
            size_hint:(.2, .1)
            pos: (root.width *0.8, root.height * 0.6)
            group: 'playerturn'
            on_press: root.exo.SetTurn(4)             
            on_press: root.add_turn(root.exo.Turn)                    
        ToggleButton:
            text:'round 5'
            id:r5
            size_hint:(.2, .1)
            pos: (root.width *0.8, root.height * 0.5)
            group: 'playerturn'
            on_press: root.exo.SetTurn(5)
            on_press: root.add_turn(root.exo.Turn)                    
        ToggleButton:
            text:'round 6'
            id:r6
            size_hint:(.2, .1)
            pos: (root.width *0.8, root.height * 0.4)
            group: 'playerturn'
            on_press: root.exo.SetTurn(6) 
            on_press: root.add_turn(root.exo.Turn)                    


        Button:
            text:'Clear!'
            id: Clear
            size_hint:(.3, .2)
            pos: (0, root.height * 0.4)
            on_press: root.exo.ClearPlayerStash()
            on_press: root.txt_inpt2 = str(root.exo.GetPlayerStash())            

            

        TextInput:
            id: txt_inpt
            text: root.txt_inpt2
            size_hint:(1, .2)
            pos: (0,0)

        Buy:



           
